on:
  push:
    branches: [ "abc" ]

jobs:
  build:
    runs-on: ubuntu-latest  # Add this line to specify the environment for the build job
    steps:
      - name: Checkout source
        uses: actions/checkout@v3
      - name: Login to docker hub
        run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
      - name: Build docker image
        run: docker build -t manhcuong99/gps .
      - name: Publish image to docker hub
        run: docker push manhcuong99/gps:latest

  deploy:
    needs: build
    runs-on: ubuntu-latest  # This is correct, no changes needed here
    steps:
      - name: Pull image from docker hub
        run: docker pull manhcuong99/gps:latest
      - name: Delete old container
        run: docker rm -f gps-container
      - name: Run docker container
        run: docker run -d -p 6268:6268 --name gps-container manhcuong99/gps
